### ISSUE TITLE
Logging to files with rotating

### ISSUE THREAD

**Issue by rdpanek** [test-stack/monitor#2]

**Comment by rdpanek** [comment]
Actually is logging via library https://www.npmjs.com/package/morgan
and output is stdout:

```
yarn start v0.24.4
$ concurrently "yarn server" "yarn client"
[0] yarn server v0.24.4
[1] yarn client v0.24.4
[1] $ react-scripts start
[0] $ babel-node server.js
[1] Starting the development server...
[1]
[0] listening on port 3001
[1] Compiled successfully!
[1]
[1] The app is running at:
[1]
[1]   http://localhost:3000/
[1]
[1] Note that the development build is not optimized.
[1] To create a production build, use yarn run build.
[1]
[0] GET /api/slots 200 32.217 ms - 499
[0] GET /api/slots 200 21.413 ms - 499
[0] GET /api/slots 200 9.767 ms - 499
[0] GET /api/slots 200 12.132 ms - 499
[0] GET /api/slots 200 7.046 ms - 499
[0] GET /api/slots 200 7.219 ms - 499
[0] GET /api/slots 200 10.350 ms - 499

```

**Comment by rdpanek** [comment]
Access is logged to access.log in /logs directory with 1d rotation, max 10 files https://github.com/test-stack/monitor/commit/2500562a639544c342f2a33597e27a96a41336c1

`/logs` isn't in git, because `.gitignore logs/` If `/logs` directory not exist, will be automatically created.

Used format:
`:method :url :status :response-time ms - :res[content-length]`

ᐰ tail -f logs/access.log
```
GET /api/slots 304 15.601 ms - -
GET /api/slots 304 19.473 ms - -
GET /api/slots 304 18.021 ms - -
GET /api/slots 200 28.980 ms - 499
GET /api/slots 200 17.217 ms - 499
```

**Comment by rdpanek** [comment]
Elasticsearch library currently logs to stdout when cluster isn't available:
```
ᐰ ELASTIC_URI=http://IP:9200 yarn server
yarn server v0.20.3
$ babel-node server.js 
listening on port 3001
Elasticsearch ERROR: 2017-05-22T13:01:15Z
  Error: Request error, retrying
  HEAD http://IP:9200/ => getaddrinfo ENOTFOUND IP IP:9200
      at Log.error (/Users/rdpanek/HTDOCS/test-stack/monitor/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/rdpanek/HTDOCS/test-stack/monitor/node_modules/elasticsearch/src/lib/transport.js:246:18)
      at HttpConnector.<anonymous> (/Users/rdpanek/HTDOCS/test-stack/monitor/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
      at ClientRequest.bound (/Users/rdpanek/HTDOCS/test-stack/monitor/node_modules/lodash/dist/lodash.js:729:21)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:310:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at connectErrorNT (net.js:1022:8)

Elasticsearch WARNING: 2017-05-22T13:01:15Z
  Unable to revive connection: http://IP:9200/

Elasticsearch WARNING: 2017-05-22T13:01:15Z
  No living connections

Trace: [Elasticsearch] cluster is down!
    at /Users/rdpanek/HTDOCS/test-stack/monitor/server.js:41:13
    at respond (/Users/rdpanek/HTDOCS/test-stack/monitor/node_modules/elasticsearch/src/lib/transport.js:314:9)
    at sendReqWithConnection (/Users/rdpanek/HTDOCS/test-stack/monitor/node_modules/elasticsearch/src/lib/transport.js:213:7)
    at next (/Users/rdpanek/HTDOCS/test-stack/monitor/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by rdpanek** [comment]
resolved https://github.com/test-stack/monitor/commit/ac0e71e22fc2f900d8e8605d033b18e0dee066b1
